const ROLES = {
  ADMIN: "ADMIN", // Global Admin
  SUB_ADMIN: "SUB_ADMIN", // Regional Admin
  PATIENT: "PATIENT",
  MEDECIN: "MEDECIN",
  PHARMACIE: "PHARMACIE",
  HOPITAL: "HOPITAL",
  LABO: "LABO",
  ASSURANCE: "ASSURANCE"
};

const REGIONS = {
  TANGIER_TETOUAN_AL_HOCEIMA: "TANGER-TETOUAN-AL HOCEIMA",
  ORIENTAL: "L'ORIENTAL",
  FES_MEKNES: "FES-MEKNES",
  RABAT_SALE_KENITRA: "RABAT-SALE-KENITRA",
  BENI_MELLAL_KHENIFRA: "BENI MELLAL-KHENIFRA",
  CASABLANCA_SETTAT: "CASABLANCA-SETTAT",
  MARRAKECH_SAFI: "MARRAKECH-SAFI",
  DRAA_TAFILALET: "DRAA-TAFILALET",
  SOUSS_MASSA: "SOUSS-MASSA",
  GUELMIM_OUED_NOUN: "GUELMIM-OUED NOUN",
  LAAYOUNE_SAKIA_EL_HAMRA: "LAAYOUNE-SAKIA EL HAMRA",
  EDDAKHLA_OUED_EDDAHAB: "EDDAKHLA-OUED EDDAHAB"
};

function normalizeRole(value) {
  return String(value || "").trim().toUpperCase();
}

module.exports = {
  ROLES,
  REGIONS,
  normalizeRole
};
